create database roja
use roja

--Types of SQL Server Exceptions--

'1.System Defined
2. User Defined'

--System Deined--
' In a System defined Exception , the exceptions (errors) are generated by the system.'

--Example--

Declare @val1 int
Declare @val2 int
Begin TRY
Set @val1=8
Set @val2 = @val1/0                
END TRY
Begin CATCH
Print 'Error Occur that is :'
Print Error_Message()
END CATCH

--USER Defined Function--

Declare @val3 int
Declare @val4 int
Begin TRY
Set @val3 = 8
Set @val4 =@val3%2
if @val4=1
print 'Error Not Occur'
else
begin
print 'Error Occur'
end
END TRY
Begin CATCH
End CATCH

create table Categories1(CategoryId int identity(1,1),CategoryName varchar(20),Description varchar(20),Picture varchar(20))
Begin Try
Insert into Categories1(CategoryId,CategoryName,Description,Picture) values (10,'Test','Test Description','Test')
End Try
Begin Catch
Select Error_Message() AS [Error Message]
, ERROR_LINE() AS ErrorLine
, ERROR_NUMBER() as [Error Number]
, Error_Severity() as [Error Severity]
, ERROR_STATE() as [Error State]
End Catch

Begin Try
Declare @x int
select @x = 1/0
print 'This statement will not be executed'
End Try
Begin Catch
print 'This error message is: ' + error_message()
End Catch
